repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.3
  hooks:
    - id: ruff
      entry: uv run ruff check
      args: [ --fix ]

    - id: ruff-format
      entry: uv run ruff format

- repo: https://github.com/pypa/pip-audit
  rev: v2.8.0
  hooks:
    - id: pip-audit
      entry: uv run pip-audit

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.0.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: []