[project]
name = "djangotutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pre-commit>=4.1.0",
    "pytest>=8.3.5",
    "pytest-watch>=4.2.0",
    "ruff>=0.9.10",
]
